package vista;

import java.awt.Color;

/**
 *
 * @author keyle_dqx9pud
 */
public class PanelComprobanteDeVenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelComprobanteDeVenta
     */
    public PanelComprobanteDeVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Texto_Nombre_Cliente = new javax.swing.JLabel();
        Texto_Nombre_Vendedor = new javax.swing.JLabel();
        Texto_Fecha_Factura = new javax.swing.JLabel();
        Texto_Metodo_De_Pago = new javax.swing.JLabel();
        Texto_Total = new javax.swing.JLabel();
        txt_NombreVendedor = new javax.swing.JLabel();
        txt_NombreCliente = new javax.swing.JLabel();
        txt_FechaFactura = new javax.swing.JLabel();
        txt_HoraFacturacion = new javax.swing.JLabel();
        txt_MetodoDePago = new javax.swing.JLabel();
        txt_Total = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_ComprobanteDeVenta = new javax.swing.JTable();
        Boton_volver = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Boton_Imprimir = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 130, 196));
        jLabel1.setText("Comprobante de ventas");
        jLabel1.setAlignmentX(101.0F);
        jLabel1.setAlignmentY(132.0F);

        Texto_Nombre_Cliente.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        Texto_Nombre_Cliente.setForeground(new java.awt.Color(63, 130, 196));
        Texto_Nombre_Cliente.setText("Nombre cliente:");

        Texto_Nombre_Vendedor.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        Texto_Nombre_Vendedor.setForeground(new java.awt.Color(63, 130, 196));
        Texto_Nombre_Vendedor.setText("Nombre vendedor:");

        Texto_Fecha_Factura.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        Texto_Fecha_Factura.setForeground(new java.awt.Color(63, 130, 196));
        Texto_Fecha_Factura.setText("Fecha factura:");

        Texto_Metodo_De_Pago.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        Texto_Metodo_De_Pago.setForeground(new java.awt.Color(63, 130, 196));
        Texto_Metodo_De_Pago.setText("Metodo de pago:");

        Texto_Total.setFont(new java.awt.Font("Lato Black", 1, 14)); // NOI18N
        Texto_Total.setText("Total: ");

        txt_NombreVendedor.setBackground(new java.awt.Color(255, 255, 255));
        txt_NombreVendedor.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        txt_NombreVendedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txt_NombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        txt_NombreCliente.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        txt_NombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txt_FechaFactura.setBackground(new java.awt.Color(255, 255, 255));
        txt_FechaFactura.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        txt_FechaFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txt_HoraFacturacion.setBackground(new java.awt.Color(255, 255, 255));
        txt_HoraFacturacion.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        txt_HoraFacturacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txt_MetodoDePago.setBackground(new java.awt.Color(255, 255, 255));
        txt_MetodoDePago.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        txt_MetodoDePago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txt_Total.setBackground(new java.awt.Color(255, 255, 255));
        txt_Total.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        txt_Total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jPanel3.setBackground(new java.awt.Color(233, 236, 239));

        Tabla_ComprobanteDeVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO UNITARIO", "DESCUENTOS", "SUBTOTAL"
            }
        ));
        jScrollPane1.setViewportView(Tabla_ComprobanteDeVenta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Boton_volver.setBackground(new java.awt.Color(170, 177, 185));
        Boton_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_volver.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                Boton_volverMouseWheelMoved(evt);
            }
        });
        Boton_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_volverMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Volver");

        javax.swing.GroupLayout Boton_volverLayout = new javax.swing.GroupLayout(Boton_volver);
        Boton_volver.setLayout(Boton_volverLayout);
        Boton_volverLayout.setHorizontalGroup(
            Boton_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boton_volverLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Boton_volverLayout.setVerticalGroup(
            Boton_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boton_volverLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Boton_Imprimir.setBackground(new java.awt.Color(63, 130, 196));
        Boton_Imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_ImprimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_ImprimirMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Imprimir");

        javax.swing.GroupLayout Boton_ImprimirLayout = new javax.swing.GroupLayout(Boton_Imprimir);
        Boton_Imprimir.setLayout(Boton_ImprimirLayout);
        Boton_ImprimirLayout.setHorizontalGroup(
            Boton_ImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boton_ImprimirLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Boton_ImprimirLayout.setVerticalGroup(
            Boton_ImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boton_ImprimirLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_NombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Texto_Nombre_Cliente)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Texto_Fecha_Factura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_FechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_HoraFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Texto_Nombre_Vendedor)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Texto_Metodo_De_Pago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_MetodoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(Texto_Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_NombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(217, 217, 217))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Boton_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(Boton_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Texto_Nombre_Cliente)
                    .addComponent(Texto_Nombre_Vendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_NombreVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_NombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Texto_Metodo_De_Pago)
                        .addComponent(Texto_Total)
                        .addComponent(txt_FechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_HoraFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_MetodoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Texto_Fecha_Factura))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Imprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_volver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_volverMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_Boton_volverMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_volverMouseWheelMoved

    private void Boton_volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_volverMouseEntered
        // TODO add your handling code here:
        Boton_volver.setBackground(new Color (216, 216,216));
    }//GEN-LAST:event_Boton_volverMouseEntered

    private void Boton_volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_volverMouseExited
        // TODO add your handling code here:
        Boton_volver.setBackground(new Color (170, 177, 185));
    }//GEN-LAST:event_Boton_volverMouseExited

    private void Boton_ImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_ImprimirMouseEntered
        // TODO add your handling code here:
        Boton_Imprimir.setBackground(new Color(0, 152, 196));
    }//GEN-LAST:event_Boton_ImprimirMouseEntered

    private void Boton_ImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_ImprimirMouseExited
        // TODO add your handling code here:
        Boton_Imprimir.setBackground(new Color(7, 103, 198));
    }//GEN-LAST:event_Boton_ImprimirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Boton_Imprimir;
    private javax.swing.JPanel Boton_volver;
    public static javax.swing.JTable Tabla_ComprobanteDeVenta;
    private javax.swing.JLabel Texto_Fecha_Factura;
    private javax.swing.JLabel Texto_Metodo_De_Pago;
    private javax.swing.JLabel Texto_Nombre_Cliente;
    private javax.swing.JLabel Texto_Nombre_Vendedor;
    private javax.swing.JLabel Texto_Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt_FechaFactura;
    private javax.swing.JLabel txt_HoraFacturacion;
    private javax.swing.JLabel txt_MetodoDePago;
    private javax.swing.JLabel txt_NombreCliente;
    private javax.swing.JLabel txt_NombreVendedor;
    private javax.swing.JLabel txt_Total;
    // End of variables declaration//GEN-END:variables
}
